### ISSUE TITLE
error ts compiling

### ISSUE THREAD

**Issue by DevDjino** [FishRoyal/futures-binance-bot#6]
src/utils.ts:56:113 - error TS2339: Property 'markPrice' does not exist on type 'MarkPrice | MarkPrice[]'.
  Property 'markPrice' does not exist on type 'MarkPrice[]'.

56         return this.floorPrecised( ((await this.usdmClient.getMarkPrice({isIsolated: "FALSE", symbol: symbol})).markPrice), pricePrecision );
                                                                                                                   ~~~~~~~~~


Found 1 error in src/utils.ts:56

**Comment by FishRoyal** [comment]
I don't know. I just cloned the repo, tried to compile and everything works. 

As written in file "./futures-binance-bot/node_modules/binance/lib/usdm-client.d.ts" the method getMarkPrice returns Promise any. So I don't know how you got the type 'MarkPrice | MarkPrice[]'. Try to reinstall this repository or check the declaration of function "getMarkPrice".

**Comment by FishRoyal** [comment]
Promise<any>

**Comment by DevDjino** [comment]
Is it normal for the node index.js to get stuck here for some time: [
  'Websocket connected',
  { category: 'binance-ws', wsKey: 'usdm_forceOrder@arr__' }
]
[
  'Websocket reconnected',
  {
    category: 'binance-ws',
    wsKey: 'usdmTestnet_userData_S2dZhi0S0MaOiUbINYBNnz97YrRcfveLMLCy4auPmVI6QV94eAMpQNkNNTwd10ED'
  }
]

**Comment by DevDjino** [comment]
or maybe it is because I'm testing on windows wsl and it's giving me these problems
